### ISSUE TITLE
Splitting main into separate readable functions

### ISSUE THREAD

**Issue by Dylan-DPC** [Miserlou/Loop#14]
Hey

I have observed that you have put the entire code inside `main()`. It is better to split them in different methods which allows the code to be more readable.

**Comment by Miserlou** [comment]
Normally I'd agree, however this is a very simple program with only a single linear control flow. It's essentially a glorified script. The only real benefit would be for testing, but I think that actually might be at the cost of readability. Thanks for your comment!
