### ISSUE TITLE
Keep track of success/fail and provide a summary

### ISSUE THREAD

**Issue by felipesere** [Miserlou/Loop#26]
I use looper to smoke out flaky tests.
As such, I run `loop 'npm run test:acceptance' --num 5` and I look what the output is.
It would be awesome if at the end I could get a summary of success (`0` exit code) vs unsuccessful (non-zero exit code) completions.

```
$ loop 'npm run test:acceptance' --num 5 --summary
...
Total: 5
Success: 4
Fail: 1
```

And then I'll know to take a closer look.
This would probably also work nicely with the other `--until-*`

With a bit of guidance I could give this a try 😄

**Comment by Miserlou** [comment]
Do it! If you're suggesting `--summary` as the interface, then it'd be great if it also contained the codes themselves, ex `Fail: 2 (-1, -4)`

**Comment by felipesere** [comment]
On it :)

**Comment by felipesere** [comment]
How does the feature now make it into crates.io?
