### ISSUE TITLE
`--until-changes` for when you wait for the stdout to alter

### ISSUE THREAD

**Issue by dkhalansky** [Miserlou/Loop#32]
A feature request that would be immensely useful to me since I often find myself waiting for something to change.

Let's say I want to be notified when my packages are finally synced to maven. Then I could do
`loop --until-changes 'curl https://repo1.maven.org/maven2/com/github/dkhalansky/paradisenglib_2.12.3/'`
This invocation would then first run the specified `curl` command, remembering some hash of the output, and then run the command periodically until the hash of the output changes. After that, the execution would end.

Or I could wait for anyone to log into my system or log out of it. Then I could do `loop --until-changes 'w -hs'`.

**Comment by Miserlou** [comment]
Great idea! Send a PR?

**Comment by Miserlou** [comment]
I've needed this feature today. I think it should maybe be `--watch`.

**Comment by norcalli** [comment]
I've needed this feature many times, but I again want it today. I can make a PR.

**Comment by Miserlou** [comment]
Godspeed You Brave Anime Person

**Comment by norcalli** [comment]
aye aye, captain

**Comment by Miserlou** [comment]
How did it go?

**Comment by norcalli** [comment]
@Miserlou oops sorry I got lost in the space time continuum for a while, but I did it https://github.com/Miserlou/Loop/pull/42

**Comment by Miserlou** [comment]
Woohoo!

**Comment by norcalli** [comment]
Should close this now.

**Comment by Miserlou** [comment]
Published in latest.
